// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_content_delivery_bucket": "remars2019-revegas-webhosting",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "https://d3b3v2rjnr7ydq.cloudfront.net",
    "aws_cognito_identity_pool_id": "us-east-1:e48cc2f0-641c-485a-9521-2cf7899f6cd1",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_0Ig7HkLsf",
    "aws_user_pools_web_client_id": "1472mpk5jmplja7g4796tc83ri",
    "aws_user_files_s3_bucket": "sigma37ad4459797941c2a8cfd6e12406c48f",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
